In [20]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [21]:
# Convert YearBuilt into Age of the House

In [22]:
df = pd.read_csv("House Price Prediction Dataset.csv")
df.sample(10)

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
291,292,4273,6,2,2,1991,Suburban,Good,No,983993
75,76,4553,1,1,1,2025,Suburban,Good,Yes,1007938
261,262,3404,5,2,1,2003,Downtown,Poor,Yes,810118
284,285,3376,6,5,2,2006,Rural,Fair,Yes,825451
51,52,3847,1,3,1,2024,Suburban,Good,No,850657
48,49,2451,5,3,2,2003,Urban,Poor,Yes,651860
163,164,3557,5,3,2,2022,Rural,Fair,Yes,838356
190,191,4552,4,3,3,2012,Downtown,Excellent,Yes,1157464
292,293,1400,2,1,2,2004,Urban,Good,No,429310
147,148,4498,6,3,3,1985,Downtown,Fair,Yes,1089822

In [23]:
df["Age"] = 2026 - df["YearBuilt"]
df.drop("YearBuilt", axis = 1, inplace = True)

In [24]:
df.sample(3)

,Id,Area,Bedrooms,Bathrooms,Floors,Location,Condition,Garage,Price,Age
92,93,2852,4,4,2,Urban,Fair,No,717429,18
239,240,1355,2,5,2,Rural,Fair,No,401257,16
54,55,1832,2,3,1,Urban,Good,Yes,499036,41

In [25]:
condition_encoder = OrdinalEncoder(
    categories = [[
        "Poor", "Fair", "Good", "Excellent"
    ]]
)
df[["Condition"]] = condition_encoder.fit_transform(df[["Condition"]])

In [26]:
df.head(10)

,Id,Area,Bedrooms,Bathrooms,Floors,Location,Condition,Garage,Price,Age
0,1,2195,5,3,2,Suburban,2.0,No,579315,38
1,2,2339,3,4,1,Suburban,3.0,No,642275,25
2,3,3602,2,4,2,Urban,2.0,Yes,876550,26
3,4,4431,3,2,1,Rural,1.0,No,932643,2
4,5,3707,2,4,1,Urban,3.0,No,891461,16
5,6,4983,1,3,1,Rural,3.0,Yes,1032606,18
6,7,4137,2,3,1,Urban,1.0,No,925607,32
7,8,4492,2,4,3,Suburban,1.0,Yes,976269,22
8,9,1140,1,5,2,Urban,1.0,Yes,455690,7
9,10,4373,6,2,3,Suburban,1.0,No,1005239,30

In [27]:
ohe = OneHotEncoder(
    drop = None,
    sparse_output = False,
)
garage_encoded = ohe.fit_transform(df[["Garage"]])

garage_cols = ohe.get_feature_names_out(["Garage"])
garage_df = pd.DataFrame(
    garage_encoded,
    columns = garage_cols,
    index = df.index
)
df.drop("Garage", axis = 1, inplace = True)
df = pd.concat([df, garage_df], axis = 1)

In [28]:
df.sample(4)

,Id,Area,Bedrooms,Bathrooms,Floors,Location,Condition,Price,Age,Garage_No,Garage_Yes
261,262,3404,5,2,1,Downtown,0.0,810118,23,0.0,1.0
238,239,2778,3,5,2,Rural,3.0,745141,9,0.0,1.0
22,23,1592,6,1,3,Rural,2.0,485580,13,0.0,1.0
121,122,3494,3,2,1,Downtown,2.0,835463,29,1.0,0.0

In [30]:
ohe = OneHotEncoder(
    drop = None,
    sparse_output = False,
)
location_encoded = ohe.fit_transform(df[["Location"]])

location_cols = ohe.get_feature_names_out(["Location"])
location_df = pd.DataFrame(
    location_encoded,
    columns = location_cols,
    index = df.index
)
df.drop("Location", axis = 1, inplace = True)
df = pd.concat([df, location_df], axis = 1)

In [31]:
df.sample(5)

,Id,Area,Bedrooms,Bathrooms,Floors,Condition,Price,Age,Garage_No,Garage_Yes,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban
212,213,3578,4,2,3,1.0,772497,26,1.0,0.0,0.0,1.0,0.0,0.0
255,256,1510,5,3,1,2.0,594948,7,0.0,1.0,1.0,0.0,0.0,0.0
254,255,749,4,3,1,0.0,343820,38,0.0,1.0,1.0,0.0,0.0,0.0
247,248,3480,4,1,3,0.0,852742,36,0.0,1.0,1.0,0.0,0.0,0.0
198,199,2270,6,3,1,1.0,543269,35,1.0,0.0,0.0,1.0,0.0,0.0

In [32]:
df.drop("Id", axis = 1, inplace = True)

In [33]:
df.sample(4)

,Area,Bedrooms,Bathrooms,Floors,Condition,Price,Age,Garage_No,Garage_Yes,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban
212,3578,4,2,3,1.0,772497,26,1.0,0.0,0.0,1.0,0.0,0.0
36,2930,4,2,1,2.0,778356,8,0.0,1.0,0.0,0.0,0.0,1.0
112,1653,2,5,3,2.0,545888,30,0.0,1.0,0.0,0.0,0.0,1.0
12,4418,2,4,1,2.0,967455,8,1.0,0.0,0.0,1.0,0.0,0.0

In [34]:
price_col = df.pop("Price")
df["Price"] = price_col

In [35]:
df.sample(4)

,Area,Bedrooms,Bathrooms,Floors,Condition,Age,Garage_No,Garage_Yes,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban,Price
21,2845,5,2,2,3.0,1,1.0,0.0,1.0,0.0,0.0,0.0,871713
162,2459,3,1,2,3.0,26,0.0,1.0,0.0,1.0,0.0,0.0,627914
55,4212,3,1,2,1.0,13,0.0,1.0,0.0,1.0,0.0,0.0,917158
104,2517,2,1,2,0.0,27,0.0,1.0,0.0,0.0,0.0,1.0,590639

In [36]:
df.to_csv("PreProcessed_Data.csv", index = False)