In [10]:
import pandas as pd

In [9]:
pd.DataFrame({
    'Yes' : [10, 30],
    'No' : [40, 20]
}, index=["Movie1", "Movie2"])

        Yes  No
Movie1   10  40
Movie2   30  20

In [ ]:
# Movie Review by Shirjan and Ankita
pd.DataFrame({
    'Shirjan' : ["Very Good", "Wonderful"],
    'Ankita' : ["Awful", "Very Bad"]
}, index =  ['Movie1', 'Movie2'])

          Shirjan    Ankita
Movie1  Very Good     Awful
Movie2  Wonderful  Very Bad