In [2]:
import pandas as pd

In [1]:
data = {
    "A" : [10, 30, 50, 10],
    "B" : [5, 40, 60, 7],
    "C" : [10, 30, 20, 90],
    "D" : [20, 50, 10, 80]
}

In [3]:
df = pd.DataFrame(data)
df

    A   B   C   D
0  10   5  10  20
1  30  40  30  50
2  50  60  20  10
3  10   7  90  80

In [ ]:
# Basic Arithmetic Operations

In [ ]:
# Addition, Subtraction, Multiplication, DIvision, Modulus
df["A + B"] = df["A"] + df["B"]
df["A - B"] = df["A"] - df["B"]
df["A * B"] = df["A"] * df["B"]
df["A / B"] = df["A"] / df["B"]
df["A mod B"] = df["A"] % df["B"]

In [6]:
df

    A   B   C   D  A + B  A - B  A * B     A / B  A mod B
0  10   5  10  20     15      5     50  2.000000        0
1  30  40  30  50     70    -10   1200  0.750000       30
2  50  60  20  10    110    -10   3000  0.833333       50
3  10   7  90  80     17      3     70  1.428571        3

In [7]:
# Statistics

In [8]:
df.mean()

A            25.000000
B            28.000000
C            37.500000
D            40.000000
A + B        53.000000
A - B        -3.000000
A * B      1080.000000
A / B         1.252976
A mod B      20.750000
dtype: float64

In [9]:
df.min()

A          10.00
B           5.00
C          10.00
D          10.00
A + B      15.00
A - B     -10.00
A * B      50.00
A / B       0.75
A mod B     0.00
dtype: float64

In [10]:
df.max()

A            50.0
B            60.0
C            90.0
D            80.0
A + B       110.0
A - B         5.0
A * B      3000.0
A / B         2.0
A mod B      50.0
dtype: float64

In [11]:
# Element wise Operations

In [13]:
import numpy as np
df["Sq_C"] = np.sqrt(df["C"])
df["Log_A"] = np.log(df["A"])
df["Exp_B"] = np.exp(df["B"])
df["Sin_D"] = np.sin(df["D"])
df

,A,B,C,D,A + B,A - B,A * B,A / B,A mod B,Sq_C,Log_A,Exp_B,Sin_D
0,10,5,10,20,15,5,50,2.000000,0,3.162278,2.302585,1.484132e+02,0.912945
1,30,40,30,50,70,-10,1200,0.750000,30,5.477226,3.401197,2.353853e+17,-0.262375
2,50,60,20,10,110,-10,3000,0.833333,50,4.472136,3.912023,1.142007e+26,-0.544021
3,10,7,90,80,17,3,70,1.428571,3,9.486833,2.302585,1.096633e+03,-0.993889

In [14]:
# apply()
def sq(x):
    return x ** 2

df["Square A"] = df["A"].apply(sq)
df

,A,B,C,D,A + B,A - B,A * B,A / B,A mod B,Sq_C,Log_A,Exp_B,Sin_D,Square A
0,10,5,10,20,15,5,50,2.000000,0,3.162278,2.302585,1.484132e+02,0.912945,100
1,30,40,30,50,70,-10,1200,0.750000,30,5.477226,3.401197,2.353853e+17,-0.262375,900
2,50,60,20,10,110,-10,3000,0.833333,50,4.472136,3.912023,1.142007e+26,-0.544021,2500
3,10,7,90,80,17,3,70,1.428571,3,9.486833,2.302585,1.096633e+03,-0.993889,100

In [ ]:
# Column Wise and Row Wise Operations

In [ ]:
df["row_sum"] = df.sum(axis=1)
df["col_sum"] = df.sum(axis=0)
df

,A,B,C,D,A + B,A - B,A * B,A / B,A mod B,Sq_C,Log_A,Exp_B,Sin_D,Square A,row_sum,col_sum
0,10,5,10,20,15,5,50,2.000000,0,3.162278,2.302585,1.484132e+02,0.912945,100,7.435819e+02,NaN
1,30,40,30,50,70,-10,1200,0.750000,30,5.477226,3.401197,2.353853e+17,-0.262375,900,4.707705e+17,NaN
2,50,60,20,10,110,-10,3000,0.833333,50,4.472136,3.912023,1.142007e+26,-0.544021,2500,2.284015e+26,NaN
3,10,7,90,80,17,3,70,1.428571,3,9.486833,2.302585,1.096633e+03,-0.993889,100,2.977715e+03,NaN

In [ ]:
col_sum = df.sum(axis=0)
col_sum_arr = np.array(col_sum, dtype="int32")
col_sum_arr

c:\Users\saile\OneDrive\Desktop\60Days\.venv\Lib\site-packages\pandas\core\series.py:901: RuntimeWarning: invalid value encountered in cast
  arr = np.array(values, dtype=dtype, copy=copy)